
   `undef APB_BUS_SIZE
   `undef APB_DW_32
   `undef AXI_TEST_INACTIVE_SIGNALS
   `undef AXI_TEST_RAND_XACTNS
   `undef DWC_NO_CDC_INIT
   `undef DWC_NO_TST_MODE
   `undef DW_HOLD_MUX_DELAY
   `undef DW_SETUP_MUX_DELAY
   `undef LEN_WIDTH
   `undef MAX_X2P_AXI_ADDR_WIDTH
   `undef MAX_X2P_AXI_DATA_WIDTH
   `undef MAX_X2P_AXI_ID_WIDTH
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM05_ATV
   `undef RM_BCM06
   `undef RM_BCM06_ATV
   `undef RM_BCM07
   `undef RM_BCM07_ATV
   `undef RM_BCM07_EFES
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM09_DP
   `undef RM_BCM09_ECC
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM21_A
   `undef RM_BCM21_ATV
   `undef RM_BCM21_CG
   `undef RM_BCM22
   `undef RM_BCM22_ATV
   `undef RM_BCM23
   `undef RM_BCM23_ATV
   `undef RM_BCM24
   `undef RM_BCM24_AP
   `undef RM_BCM25
   `undef RM_BCM25_ATV
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM35
   `undef RM_BCM35_T
   `undef RM_BCM36
   `undef RM_BCM36_NHS
   `undef RM_BCM37
   `undef RM_BCM38
   `undef RM_BCM38_ADP
   `undef RM_BCM38_AP
   `undef RM_BCM38_ECC
   `undef RM_BCM39
   `undef RM_BCM40
   `undef RM_BCM41
   `undef RM_BCM42
   `undef RM_BCM43
   `undef RM_BCM43_NRO
   `undef RM_BCM44
   `undef RM_BCM44_NRO
   `undef RM_BCM46_A
   `undef RM_BCM46_AA
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM46_E
   `undef RM_BCM46_F
   `undef RM_BCM47
   `undef RM_BCM48
   `undef RM_BCM48_DM
   `undef RM_BCM48_SV
   `undef RM_BCM49
   `undef RM_BCM49_SV
   `undef RM_BCM50
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM55_C
   `undef RM_BCM56
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM60
   `undef RM_BCM62
   `undef RM_BCM63
   `undef RM_BCM64
   `undef RM_BCM64_TD
   `undef RM_BCM65
   `undef RM_BCM65_ATV
   `undef RM_BCM65_TD
   `undef RM_BCM66
   `undef RM_BCM66_EFES
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM74
   `undef RM_BCM76
   `undef RM_BCM77
   `undef RM_BCM78
   `undef RM_BCM79
   `undef RM_BCM85
   `undef RM_BCM86
   `undef RM_BCM87
   `undef RM_BCM90
   `undef RM_BCM95
   `undef RM_BCM95_E
   `undef RM_BCM95_I
   `undef RM_BCM95_IE
   `undef RM_BCM98
   `undef RM_BCM99
   `undef RM_BCM99_N
   `undef RM_BVM01
   `undef RM_BVM02
   `undef RM_ENDIAN
   `undef RM_SVA01
   `undef RM_SVA02
   `undef RM_SVA03
   `undef RM_SVA04
   `undef RM_SVA05
   `undef RM_SVA06
   `undef RM_SVA07
   `undef RM_SVA99
   `undef SIM_APB_CLK_PERIOD
   `undef SIM_AXI_CLK_PERIOD
   `undef SIM_A_CLK_PERIOD
   `undef SIM_A_END_ADDR_S1
   `undef SIM_A_END_ADDR_S2
   `undef SIM_A_END_ADDR_S3
   `undef SIM_A_START_ADDR_S1
   `undef SIM_A_START_ADDR_S2
   `undef SIM_A_START_ADDR_S3
   `undef SIM_A_TTICK_CLK_CYCLES
   `undef SIM_B_CLK_PERIOD
   `undef SIM_B_END_ADDR_S1
   `undef SIM_B_END_ADDR_S2
   `undef SIM_B_END_ADDR_S3
   `undef SIM_B_START_ADDR_S1
   `undef SIM_B_START_ADDR_S2
   `undef SIM_B_START_ADDR_S3
   `undef SIM_B_TTICK_CLK_CYCLES
   `undef SIM_DEBUG_LEVEL
   `undef SIM_RAND_SEED
   `undef SIM_USE_CC_RAND_SEED
   `undef SIM_USE_VARIABLE_SEED
   `undef USE_FOUNDATION
   `undef X2P_ALLOW_SPARSE_TRANSFER
   `undef X2P_ALLOW_SPARSE_TRANSFER_EN
   `undef X2P_APB_ADDR_WIDTH
   `undef X2P_APB_DATA_WIDTH
   `undef X2P_APB_SIZE
   `undef X2P_APB_WSTRB_WIDTH
   `undef X2P_AXI4_INTERFACE
   `undef X2P_AXI_AW
   `undef X2P_AXI_BLW
   `undef X2P_AXI_BLW_8
   `undef X2P_AXI_DW
   `undef X2P_AXI_ENDIANNESS
   `undef X2P_AXI_END_ADDR
   `undef X2P_AXI_INTERFACE_TYPE
   `undef X2P_AXI_LTW
   `undef X2P_AXI_NUM_MASTERS
   `undef X2P_AXI_NUM_SLAVES
   `undef X2P_AXI_SIDW
   `undef X2P_AXI_START_ADDR
   `undef X2P_AXI_WDFIFO_WIDTH
   `undef X2P_AXI_WSTRB_WIDTH
   `undef X2P_CLK_MODE
   `undef X2P_CMD_ADDR_WIDTH
   `undef X2P_CMD_QUEUE_DEPTH
   `undef X2P_CMD_QUEUE_WIDTH
   `undef X2P_DEFAULT_VAL
   `undef X2P_DUAL_CLK_SYNC_DEPTH
   `undef X2P_END_PADDR_32_S0
   `undef X2P_END_PADDR_32_S1
   `undef X2P_END_PADDR_32_S10
   `undef X2P_END_PADDR_32_S11
   `undef X2P_END_PADDR_32_S12
   `undef X2P_END_PADDR_32_S13
   `undef X2P_END_PADDR_32_S14
   `undef X2P_END_PADDR_32_S15
   `undef X2P_END_PADDR_32_S2
   `undef X2P_END_PADDR_32_S3
   `undef X2P_END_PADDR_32_S4
   `undef X2P_END_PADDR_32_S5
   `undef X2P_END_PADDR_32_S6
   `undef X2P_END_PADDR_32_S7
   `undef X2P_END_PADDR_32_S8
   `undef X2P_END_PADDR_32_S9
   `undef X2P_END_PADDR_S0
   `undef X2P_END_PADDR_S1
   `undef X2P_END_PADDR_S10
   `undef X2P_END_PADDR_S11
   `undef X2P_END_PADDR_S12
   `undef X2P_END_PADDR_S13
   `undef X2P_END_PADDR_S14
   `undef X2P_END_PADDR_S15
   `undef X2P_END_PADDR_S2
   `undef X2P_END_PADDR_S3
   `undef X2P_END_PADDR_S4
   `undef X2P_END_PADDR_S5
   `undef X2P_END_PADDR_S6
   `undef X2P_END_PADDR_S7
   `undef X2P_END_PADDR_S8
   `undef X2P_END_PADDR_S9
   `undef X2P_HAS_APB3
   `undef X2P_IDLE_VAL
   `undef X2P_IS_APB3_S0
   `undef X2P_IS_APB3_S1
   `undef X2P_IS_APB3_S10
   `undef X2P_IS_APB3_S11
   `undef X2P_IS_APB3_S12
   `undef X2P_IS_APB3_S13
   `undef X2P_IS_APB3_S14
   `undef X2P_IS_APB3_S15
   `undef X2P_IS_APB3_S2
   `undef X2P_IS_APB3_S3
   `undef X2P_IS_APB3_S4
   `undef X2P_IS_APB3_S5
   `undef X2P_IS_APB3_S6
   `undef X2P_IS_APB3_S7
   `undef X2P_IS_APB3_S8
   `undef X2P_IS_APB3_S9
   `undef X2P_LOG2_LOWPWR_NOPX_CNT
   `undef X2P_LOWPWR_HS_IF
   `undef X2P_LOWPWR_LEGACY_IF
   `undef X2P_LOWPWR_NOPX_CNT
   `undef X2P_MAX_AXI_SIZE
   `undef X2P_NUM_APB_SLAVES
   `undef X2P_READ_BUFFER_DEPTH
   `undef X2P_START_PADDR_32_S0
   `undef X2P_START_PADDR_32_S1
   `undef X2P_START_PADDR_32_S10
   `undef X2P_START_PADDR_32_S11
   `undef X2P_START_PADDR_32_S12
   `undef X2P_START_PADDR_32_S13
   `undef X2P_START_PADDR_32_S14
   `undef X2P_START_PADDR_32_S15
   `undef X2P_START_PADDR_32_S2
   `undef X2P_START_PADDR_32_S3
   `undef X2P_START_PADDR_32_S4
   `undef X2P_START_PADDR_32_S5
   `undef X2P_START_PADDR_32_S6
   `undef X2P_START_PADDR_32_S7
   `undef X2P_START_PADDR_32_S8
   `undef X2P_START_PADDR_32_S9
   `undef X2P_START_PADDR_S0
   `undef X2P_START_PADDR_S1
   `undef X2P_START_PADDR_S10
   `undef X2P_START_PADDR_S11
   `undef X2P_START_PADDR_S12
   `undef X2P_START_PADDR_S13
   `undef X2P_START_PADDR_S14
   `undef X2P_START_PADDR_S15
   `undef X2P_START_PADDR_S2
   `undef X2P_START_PADDR_S3
   `undef X2P_START_PADDR_S4
   `undef X2P_START_PADDR_S5
   `undef X2P_START_PADDR_S6
   `undef X2P_START_PADDR_S7
   `undef X2P_START_PADDR_S8
   `undef X2P_START_PADDR_S9
   `undef X2P_VERIF_EN
   `undef X2P_WRITE_BUFFER_DEPTH
   `undef X2P_WRITE_RESP_BUFFER_DEPTH
   `undef __GUARD__DW_AXI_X2P_ALL_INCLUDES__VH__
   `undef __GUARD__DW_AXI_X2P_BCM_PARAMS__VH__
   `undef __GUARD__DW_AXI_X2P_CC_CONSTANTS__VH__
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
